name: Test

on: [push, pull_request]

jobs:
  tuple:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        foo: [
          [A1, A2],
          [B1, B2],
          [C1, C2]
        ]
      fail-fast: false
    env:
      FIRST: ${{ matrix.foo[0] }}
      SECOND: ${{ matrix.foo[1] }}
    steps:
    - uses: actions/checkout@v2
    - name: Print
      run: echo $FIRST $SECOND
